export const fallbackServices = [
  {
    id: 'fallback-blue-books',
    name: 'Blue Books',
    icon: 'menu_book',
    enabled: true,
    color: '#4a40e0',
    background: '#eef2ff',
  },
  {
    id: 'fallback-color-printing',
    name: 'Color Printing',
    icon: 'print',
    enabled: true,
    color: '#00628c',
    background: '#e9f8ff',
  },
  {
    id: 'fallback-no-due-forms',
    name: 'No Due Forms',
    icon: 'description',
    enabled: true,
    color: '#006947',
    background: '#e8f7ef',
  },
  {
    id: 'fallback-lab-manuals',
    name: 'Lab Manuals',
    icon: 'science',
    enabled: true,
    color: '#b41340',
    background: '#fff1f4',
  },
  {
    id: 'fallback-project-reports',
    name: 'Project Reports',
    icon: 'assignment',
    enabled: true,
    color: '#7c3aed',
    background: '#f3e8ff',
  },
  {
    id: 'fallback-assignment-print',
    name: 'Assignment Print',
    icon: 'article',
    enabled: true,
    color: '#2563eb',
    background: '#dbeafe',
  },
  {
    id: 'fallback-thesis-binding',
    name: 'Thesis Binding',
    icon: 'book_2',
    enabled: true,
    color: '#9333ea',
    background: '#ede9fe',
  },
  {
    id: 'fallback-certificates',
    name: 'Certificate Prints',
    icon: 'workspace_premium',
    enabled: true,
    color: '#ca8a04',
    background: '#fef3c7',
  },
  {
    id: 'fallback-id-card',
    name: 'ID Card Print',
    icon: 'badge',
    enabled: true,
    color: '#0f766e',
    background: '#ccfbf1',
  },
  {
    id: 'fallback-xerox',
    name: 'Xerox Copies',
    icon: 'content_copy',
    enabled: true,
    color: '#1d4ed8',
    background: '#dbeafe',
  },
  {
    id: 'fallback-photo-print',
    name: 'Photo Printing',
    icon: 'photo_camera',
    enabled: true,
    color: '#db2777',
    background: '#fce7f3',
  },
]
